#! /bin/sh
### BEGIN INIT INFO
# Provides:          rc.local
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run /etc/rc.local if it exist
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions


case "$1" in
    start)
	echo "Starting sweeter web app..."
        su ubuntu -c " cd /home/ubuntu/go/src/sweeter-web/; chmod +x sweeter-web; /usr/bin/nohup ./sweeter-web 2>/dev/null & "  
        ;;
    stop)
	echo "Stopping sweeter web app..."
	su ubuntu -c " kill -9 $(pidof sweeter-web) "
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
